def run_wizard_generate(
    input_text: str,
    output: str,
    skip_review: bool,
    preview: bool,
    date: str,
    cite: bool,
) -> None:
    from src.cli.generate import generate as _generate

    _generate(
        input_text=input_text,
        output_path=output,
        skip_review=skip_review,
        max_rounds=3,
        convergence=False,
        skip_info=False,
        show_rounds=False,
        batch="",
        workers=1,
        preview=preview,
        retries=1,
        save_markdown=False,
        quiet=False,
        confirm=False,
        export_report="",
        save_versions=False,
        from_file="",
        dry_run=False,
        lang_check=False,
        auto_sender=False,
        estimate=False,
        summary=False,
        priority_tag="",
        cc="",
        watermark="",
        header="",
        footnote="",
        ref_number="",
        encoding="utf-8",
        date=date,
        sign="",
        attachment="",
        classification="",
        template_name="",
        receiver_title="",
        speed="normal",
        page_break=False,
        margin="standard",
        line_spacing="1.5",
        font_size="12",
        duplex="off",
        orientation="portrait",
        paper_size="A4",
        columns="1",
        seal="none",
        copy_count="1",
        draft_mark="none",
        urgency_label="normal",
        lang="zh-TW",
        header_logo="",
        disclaimer="",
        cite=cite,
    )
